### ISSUE TITLE
Segmentation fault by refocusing the input fields in webpages

### ISSUE THREAD

**Issue by arpio23** [cutie-shell/cutie-browser#1]
Tested on different pages.

Reproduce:
1. Start the browser
2. Type anything in the duckduckgo search field.
3. Touch anywhere to remove the focus from the search field
4. Touch in the search field again, browser crashes.

**Comment by erikinkinen** [comment]
Sometimes moving focus is not necessary and moving cursor is enough.

**Comment by arpio23** [comment]
Same happens if I run the browser in wayfire. I did not debug more, only checked the output in the terminal. Only extra lines there:

xkbcommon: ERROR: couldn't find a Compose file for locale "en_US.UTF8" (mapped to "en_US.UTF8")
qt.xkb.compose: failed to create compose table
Segmentation fault

I think its qtwebengine bug. Was it happening also with qt5?

**Comment by erikinkinen** [comment]
> Same happens if I run the browser in wayfire. I did not debug more, only checked the output in the terminal. Only extra lines there:

Interesting... We should take a look if anyone else seems to know about this on the Internet.

> xkbcommon: ERROR: couldn't find a Compose file for locale "en_US.UTF8" (mapped to "en_US.UTF8") qt.xkb.compose: failed to create compose table Segmentation fault
> 
> I think its qtwebengine bug. Was it happening also with qt5?

No, it happens only on qt6. Maybe trying on qutebrowser would be worth it.

Nevertheless, it did not happen on Chromium. So, it is (again) a qt6 and chromium integration issue.

**Comment by arpio23** [comment]
I cannot compile the examples from qt with our dev packages:

CMake Error at /usr/lib/aarch64-linux-gnu/cmake/Qt6Qml/QmlPlugins/Qt6qtwebenginequickdelegatespluginTargets.cmake:96 (message):
  The imported target "Qt6::qtwebenginequickdelegatesplugin" references the
  file

     "/usr/lib/aarch64-linux-gnu/qt6/qml/QtWebEngine/ControlsDelegates/libqtwebenginequickdelegatesplugin.so"


If don't link against webengine
https://github.com/cutie-shell/qt6-webengine/blob/357a169f6dba621c46f9cb56e7314d19ff5e9001/examples/webenginequick/minimal/CMakeLists.txt#L26

And remove the
https://github.com/cutie-shell/qt6-webengine/blob/357a169f6dba621c46f9cb56e7314d19ff5e9001/examples/webenginequick/minimal/main.cpp#L6

https://github.com/cutie-shell/qt6-webengine/blob/357a169f6dba621c46f9cb56e7314d19ff5e9001/examples/webenginequick/minimal/main.cpp#L12

It compiles but same crash on refocus
